# -*- coding: utf-8 -*-
"""plotVetores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oWHnOqElrZdgDg5p77or2YeEd_9i9mnr

## Curso Álgebra Linear Com Python

Instrutor: Rafael F. V. C. Santos

E-mail: rafaelfvcs@mail.com
"""

import numpy as np
import matplotlib.pyplot as plt

def plotVectors(vecs, cols, alpha=1):
    """
    Plot set of vectors.

    Parameters
    ----------
    vecs : array-like
        Coordinates of the vectors to plot. Each vectors is in an array. For
        instance: [[1, 3], [2, 2]] can be used to plot 2 vectors.
    cols : array-like
        Colors of the vectors. For instance: ['red', 'blue'] will display the
        first vector in red and the second in blue.
    alpha : float
        Opacity of vectors

    Returns:

    fig : instance of matplotlib.figure.Figure
        The figure of the vectors
    """
    plt.figure()
    plt.axvline(x=0, color='#A9A9A9', zorder=0)
    plt.axhline(y=0, color='#A9A9A9', zorder=0)

    for i in range(len(vecs)):
        x = np.concatenate([[0,0],vecs[i]])
        plt.quiver([x[0]],
                   [x[1]],
                   [x[2]],
                   [x[3]],
                   angles='xy', scale_units='xy', scale=1, color=cols[i],
                  alpha=alpha)

laranja = '#FF9A13'
azul = '#1190FF'

res = '#11FFFF'

plotVectors([[2,3], [4,-1], [6,2]], [laranja, azul, res])


plt.xlim(0,7)
plt.ylim(-5,5)

# Cores

cor1 = '#FF0000'
cor2 = '#0FF000'

corRes = '#11FFFF'


u = np.array([2,3])
v = np.array([3,1])

r = u+v


plotVectors([u, v, r], [cor1, cor2, corRes])

plt.xlim(0,6)
plt.ylim(-5,6)



